# トークン枝刈り

# layer_id=3で50%、layer_id=6で75%、layer_id=9で87.5%のトークン枝刈り
python3 main.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64 --epochs 20 --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.5 0.25 0.125 --ratio_weight 5.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --output_dir outputs/token/base-rate50

# layer_id=3で30%、layer_id=6で51%、layer_id=9で65.7%のトークン枝刈り
python3 main.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64 --epochs 20 --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --output_dir outputs/token/base-rate50

# MLP構造化枝刈り

# L1を使用。90%枝刈り
python3 structured_pruning/run_mlp_pruning.py --checkpoint-in outputs/baseline_cifar100-re/checkpoint-best.pth --checkpoint-out outputs/mlp/mlp10/structured.pth --model deit-b --num-classes 100 --prune-ratio 0.9 --min-channels 96 --disable-token-pruning

python3 main.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64 --epochs 20 --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 1.0 1.0 1.0 --ratio_weight 0.0 --structured-mlp-only --finetune outputs/mlp/mlp10/structured.pth --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --output_dir outputs/mlp/mlp10

# L1を使用。50%枝刈り
python3 structured_pruning/run_mlp_pruning.py --checkpoint-in outputs/baseline_cifar100-re/checkpoint-best.pth --checkpoint-out outputs/mlp/mlp50/structured.pth --model deit-b --num-classes 100 --prune-ratio 0.5 --min-channels 96 --disable-token-pruning

python3 main.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64 --epochs 20 --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 1.0 1.0 1.0 --ratio_weight 0.0 --structured-mlp-only --finetune outputs/mlp/mlp50/structured.pth --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --output_dir outputs/mlp/mlp50



# 勾配ベース枝刈り。勾配はL_clsなしで収集。90%枝刈り
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 1.0 1.0 1.0 --ratio_weight 0.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --token-train-epochs 0 --grad-collect-epochs 1 --struct-keep-ratio 0.1 --struct-min-channels 96 --finetune-epochs 0 --experiment-root outputs/grad_prune_wo_loss_cls/mlp10

python3 main.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64 --epochs 20 --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 1.0 1.0 1.0 --ratio_weight 0.0 --structured-mlp-only --finetune outputs/grad_prune_wo_loss_cls/mlp10/structured_prune/checkpoint-grad-pruned.pth --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --output_dir outputs/grad_prune_wo_loss_cls/mlp10/finetune

# 勾配ベース枝刈り。勾配はL_clsなしで収集。50%枝刈り
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 1.0 1.0 1.0 --ratio_weight 0.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --token-train-epochs 0 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-min-channels 96 --finetune-epochs 0 --experiment-root outputs/grad_prune_wo_loss_cls/mlp50

python3 main.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64 --epochs 20 --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 1.0 1.0 1.0 --ratio_weight 0.0 --structured-mlp-only --finetune outputs/grad_prune_wo_loss_cls/mlp50/structured_prune/checkpoint-grad-pruned.pth --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --output_dir outputs/grad_prune_wo_loss_cls/mlp50/finetune



# 勾配ベース枝刈り。勾配はL_clsを含む全てのロスで収集。90%枝刈り
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 1.0 1.0 1.0 --ratio_weight 0.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 11 --token-train-epochs 0 --grad-collect-epochs 1 --struct-keep-ratio 0.1 --struct-min-channels 96 --finetune-epochs 0 --experiment-root outputs/grad_prune_with_loss_cls/mlp10

python3 main.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64 --epochs 20 --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 1.0 1.0 1.0 --ratio_weight 0.0 --structured-mlp-only --finetune outputs/grad_prune_with_loss_cls/mlp10/structured_prune/checkpoint-grad-pruned.pth --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --output_dir outputs/grad_prune_with_loss_cls/mlp10/finetune

# 勾配ベース枝刈り。勾配はL_clsを含む全てのロスで収集。50%枝刈り
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 1.0 1.0 1.0 --ratio_weight 0.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 11 --token-train-epochs 0 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-min-channels 96 --finetune-epochs 0 --experiment-root outputs/grad_prune_with_loss_cls/mlp50

python3 main.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64 --epochs 20 --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 1.0 1.0 1.0 --ratio_weight 0.0 --structured-mlp-only --finetune outputs/grad_prune_with_loss_cls/mlp50/structured_prune/checkpoint-grad-pruned.pth --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --output_dir outputs/grad_prune_with_loss_cls/mlp50/finetune


# 勾配ベース枝刈り。勾配はL_clsのみで収集。90%枝刈り
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 1.0 1.0 1.0 --ratio_weight 0.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 11 --token-train-epochs 0 --grad-collect-epochs 1 --struct-keep-ratio 0.1 --struct-min-channels 96 --finetune-epochs 0 --prune-grad-L-cls --experiment-root outputs/grad_prune_with_only_loss_cls/mlp10

python3 main.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64 --epochs 20 --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 1.0 1.0 1.0 --ratio_weight 0.0 --structured-mlp-only --finetune outputs/grad_prune_with_only_loss_cls/mlp10/structured_prune/checkpoint-grad-pruned.pth --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --output_dir outputs/grad_prune_with_only_loss_cls/mlp10/finetune

# 勾配ベース枝刈り。勾配はL_clsのみで収集。50%枝刈り
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 1.0 1.0 1.0 --ratio_weight 0.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 11 --token-train-epochs 0 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-min-channels 96 --finetune-epochs 0 --prune-grad-L-cls --experiment-root outputs/grad_prune_with_only_loss_cls/mlp50

python3 main.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64 --epochs 20 --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 1.0 1.0 1.0 --ratio_weight 0.0 --structured-mlp-only --finetune outputs/grad_prune_with_only_loss_cls/mlp50/structured_prune/checkpoint-grad-pruned.pth --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --output_dir outputs/grad_prune_with_only_loss_cls/mlp50/finetune



# 勾配ベース枝刈り。勾配はLceのみで収集。90%枝刈り
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 1.0 1.0 1.0 --ratio_weight 0.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --token-train-epochs 0 --grad-collect-epochs 1 --struct-keep-ratio 0.1 --struct-min-channels 96 --finetune-epochs 0 --distill-weight 0.0 --experiment-root outputs/grad_prune_only_Lce/mlp10

python3 main.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64 --epochs 20 --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 1.0 1.0 1.0 --ratio_weight 0.0 --structured-mlp-only --finetune outputs/grad_prune_only_Lce/mlp10/structured_prune/checkpoint-grad-pruned.pth --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --output_dir outputs/grad_prune_only_Lce/mlp10/finetune

# 勾配ベース枝刈り。勾配はLceのみで収集。50%枝刈り
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 1.0 1.0 1.0 --ratio_weight 0.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --token-train-epochs 0 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-min-channels 96 --finetune-epochs 0 --distill-weight 0.0 --experiment-root outputs/grad_prune_only_Lce/mlp50

python3 main.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64 --epochs 20 --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 1.0 1.0 1.0 --ratio_weight 0.0 --structured-mlp-only --finetune outputs/grad_prune_only_Lce/mlp50/structured_prune/checkpoint-grad-pruned.pth --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --output_dir outputs/grad_prune_only_Lce/mlp50/finetune




# Token+Struct
# トークン枝刈り
python3 main.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64 --epochs 20 --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --output_dir outputs/token/base-rate70
# Magnitudepruning
python3 structured_pruning/run_mlp_pruning.py --checkpoint-in outputs_20260317/token/base-rate70/checkpoint-best.pth --checkpoint-out outputs/token_to_mlp/magnitude/token70_mlp50/prune_checkpoint.pth --model deit-b --num-classes 100 --prune-ratio 0.5 --min-channels 96 --disable-token-pruning
# 再学習
python3 main.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64 --epochs 20 --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/token_to_mlp/magnitude/token70_mlp50/prune_checkpoint.pth --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --use_checkpoint true --output_dir outputs/token_to_mlp/magnitude/token70_mlp50




# 篠田様の方法 L_clsなし
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-min-channels 96 --finetune-epochs 20 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --experiment-root outputs/shinoda_wo_loss_cls

# 篠田様の方法 L_clsあり (枝刈り時の勾配はL_clsを含む全てのロスで収集)
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 11 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-min-channels 96 --finetune-epochs 20 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --experiment-root outputs/shinoda_with_loss_cls_type1

# 篠田様の方法 L_clsあり (枝刈り時の勾配はL_clsのみで収集)
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 11 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-min-channels 96 --finetune-epochs 20 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --prune-grad-L-cls --experiment-root outputs/shinoda_with_loss_cls_type2



# 交互段階的ハイブリッド枝刈り L_clsなし
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.7 0.7 --ratio_weight 5.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --cls-sim-layers 3 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 0 1 2 3 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --experiment-root outputs/hybrid_pruning_b_wo_loss_cls_step1
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.49 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_wo_loss_cls_step1/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --cls-sim-layers 6 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 4 5 6 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 4 5 6 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --experiment-root outputs/hybrid_pruning_b_wo_loss_cls_step2
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_wo_loss_cls_step2/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --cls-sim-layers 9 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 7 8 9 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 7 8 9 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --experiment-root outputs/hybrid_pruning_b_wo_loss_cls_step3
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_wo_loss_cls_step3/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --cls-sim-layers 11 --token-train-epochs 0 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 10 11 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 10 11 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --experiment-root outputs/hybrid_pruning_b_wo_loss_cls_step4


# 交互段階的ハイブリッド枝刈り L_clsなし classifierも更新
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.7 0.7 --ratio_weight 5.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --cls-sim-layers 3 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 0 1 2 3 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 --update-classifier --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --experiment-root outputs/hybrid_pruning_b_wo_loss_cls_update_classifier_step1
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.49 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_wo_loss_cls_update_classifier_step1/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --cls-sim-layers 6 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 4 5 6 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 4 5 6 --update-classifier --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --experiment-root outputs/hybrid_pruning_b_wo_loss_cls_update_classifier_step2
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_wo_loss_cls_update_classifier_step2/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --cls-sim-layers 9 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 7 8 9 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 7 8 9 --update-classifier --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --experiment-root outputs/hybrid_pruning_b_wo_loss_cls_update_classifier_step3
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_wo_loss_cls_update_classifier_step3/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --cls-sim-layers 11 --token-train-epochs 0 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 10 11 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 10 11 --update-classifier --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --experiment-root outputs/hybrid_pruning_b_wo_loss_cls_update_classifier_step4


# 交互段階的ハイブリッド枝刈り L_clsなし 対象ブロックより入力側も更新
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.7 0.7 --ratio_weight 5.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --cls-sim-layers 3 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 0 1 2 3 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --experiment-root outputs/hybrid_pruning_b_wo_loss_cls_update_lower_step1
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.49 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_wo_loss_cls_update_lower_step1/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --cls-sim-layers 6 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 4 5 6 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 4 5 6 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --experiment-root outputs/hybrid_pruning_b_wo_loss_cls_update_lower_step2
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_wo_loss_cls_update_lower_step2/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --cls-sim-layers 9 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 7 8 9 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 4 5 6 7 8 9 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --experiment-root outputs/hybrid_pruning_b_wo_loss_cls_update_lower_step3
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_wo_loss_cls_update_lower_step3/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --cls-sim-layers 11 --token-train-epochs 0 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 10 11 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 4 5 6 7 8 9 10 11 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --experiment-root outputs/hybrid_pruning_b_wo_loss_cls_update_lower_step4


# 交互段階的ハイブリッド枝刈り L_clsなし classifierも更新 対象ブロックより入力側も更新
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.7 0.7 --ratio_weight 5.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --cls-sim-layers 3 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 0 1 2 3 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 --update-classifier --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --experiment-root outputs/hybrid_pruning_b_wo_loss_cls_update_lower_and_classifier_step1
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.49 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_wo_loss_cls_update_lower_and_classifier_step1/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --cls-sim-layers 6 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 4 5 6 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 4 5 6 --update-classifier --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --experiment-root outputs/hybrid_pruning_b_wo_loss_cls_update_lower_and_classifier_step2
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_wo_loss_cls_update_lower_and_classifier_step2/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --cls-sim-layers 9 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 7 8 9 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 4 5 6 7 8 9 --update-classifier --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --experiment-root outputs/hybrid_pruning_b_wo_loss_cls_update_lower_and_classifier_step3
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_wo_loss_cls_update_lower_and_classifier_step3/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.0 --cls-sim-layers 11 --token-train-epochs 0 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 10 11 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 4 5 6 7 8 9 10 11 --update-classifier --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --experiment-root outputs/hybrid_pruning_b_wo_loss_cls_update_lower_and_classifier_step4






# 交互段階的ハイブリッド枝刈り L_clsあり
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.7 0.7 --ratio_weight 5.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 3 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 0 1 2 3 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --prune-grad-L-cls --experiment-root outputs/hybrid_pruning_b_with_loss_cls_type2_step1
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.49 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_with_loss_cls_type2_step1/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 6 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 4 5 6 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 4 5 6 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --prune-grad-L-cls --experiment-root outputs/hybrid_pruning_b_with_loss_cls_type2_step2
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_with_loss_cls_type2_step2/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 9 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 7 8 9 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 7 8 9 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --prune-grad-L-cls --experiment-root outputs/hybrid_pruning_b_with_loss_cls_type2_step3
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_with_loss_cls_type2_step3/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 11 --token-train-epochs 0 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 10 11 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 10 11 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --prune-grad-L-cls --experiment-root outputs/hybrid_pruning_b_with_loss_cls_type2_step4

## 交互段階的ハイブリッド枝刈り L_clsあり classifierも更新
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.7 0.7 --ratio_weight 5.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 3 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 0 1 2 3 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 --update-classifier --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --prune-grad-L-cls --experiment-root outputs/hybrid_pruning_b_with_loss_cls_type2_update_classifier_step1
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.49 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_with_loss_cls_type2_update_classifier_step1/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 6 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 4 5 6 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 4 5 6 --update-classifier --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --prune-grad-L-cls --experiment-root outputs/hybrid_pruning_b_with_loss_cls_type2_update_classifier_step2
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_with_loss_cls_type2_update_classifier_step2/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 9 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 7 8 9 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 7 8 9 --update-classifier --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --prune-grad-L-cls --experiment-root outputs/hybrid_pruning_b_with_loss_cls_type2_update_classifier_step3
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_with_loss_cls_type2_update_classifier_step3/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 11 --token-train-epochs 0 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 10 11 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 10 11 --update-classifier --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --prune-grad-L-cls --experiment-root outputs/hybrid_pruning_b_with_loss_cls_type2_update_classifier_step4


## 交互段階的ハイブリッド枝刈り L_clsあり 対象ブロックより入力側も更新
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.7 0.7 --ratio_weight 5.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 3 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 0 1 2 3 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --prune-grad-L-cls --experiment-root outputs/hybrid_pruning_b_with_loss_cls_type2_update_lower_step1
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.49 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_with_loss_cls_type2_update_lower_step1/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 6 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 4 5 6 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 4 5 6 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --prune-grad-L-cls --experiment-root outputs/hybrid_pruning_b_with_loss_cls_type2_update_lower_step2
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_with_loss_cls_type2_update_lower_step2/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 9 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 7 8 9 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 4 5 6 7 8 9 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --prune-grad-L-cls --experiment-root outputs/hybrid_pruning_b_with_loss_cls_type2_update_lower_step3
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_with_loss_cls_type2_update_lower_step3/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 11 --token-train-epochs 0 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 10 11 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 4 5 6 7 8 9 10 11 --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --prune-grad-L-cls --experiment-root outputs/hybrid_pruning_b_with_loss_cls_type2_update_lower_step4


## 交互段階的ハイブリッド枝刈り L_clsあり classifierも更新 対象ブロックより入力側も更新
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.7 0.7 --ratio_weight 5.0 --finetune outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 3 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 0 1 2 3 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 --update-classifier --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --prune-grad-L-cls --experiment-root outputs/hybrid_pruning_b_with_loss_cls_type2_update_lower_and_classifier_step1
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.49 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_with_loss_cls_type2_update_lower_and_classifier_step1/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 6 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 4 5 6 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 4 5 6 --update-classifier --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --prune-grad-L-cls --experiment-root outputs/hybrid_pruning_b_with_loss_cls_type2_update_lower_and_classifier_step2
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_with_loss_cls_type2_update_lower_and_classifier_step2/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 9 --token-train-epochs 20 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 7 8 9 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 4 5 6 7 8 9 --update-classifier --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --prune-grad-L-cls --experiment-root outputs/hybrid_pruning_b_with_loss_cls_type2_update_lower_and_classifier_step3
python3 structured_pruning/hybrid_pruning.py --model deit-b --input_size 224 --data_set CIFAR --data_path ./data --nb_classes 100 --batch_size 64  --lr 2.5e-4 --warmup_steps 500 --weight_decay 0.05 --drop_path 0.2 --token-rate 0.7 0.49 0.343 --ratio_weight 5.0 --finetune outputs/hybrid_pruning_b_with_loss_cls_type2_update_lower_and_classifier_step3/finetune/checkpoint-best.pth --cls-sim-ref outputs/baseline_cifar100-re/checkpoint-best.pth --cls-sim-weight 0.05 --cls-sim-layers 11 --token-train-epochs 0 --grad-collect-epochs 1 --struct-keep-ratio 0.5 --struct-prune-layers 10 11 --struct-min-channels 96 --finetune-epochs 20 --finetune-layers 0 1 2 3 4 5 6 7 8 9 10 11 --update-classifier --teacher_path outputs/baseline_cifar100-re/checkpoint-best.pth --prune-grad-L-cls --experiment-root outputs/hybrid_pruning_b_with_loss_cls_type2_update_lower_and_classifier_step4

